/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSpecialtyRouteRouteImport } from './routes/app/specialty/route'
import { Route as AppHomeRouteRouteImport } from './routes/app/home/route'
import { Route as AppHistoryRouteRouteImport } from './routes/app/history/route'
import { Route as AppBookOfflineRouteRouteImport } from './routes/app/book-offline/route'
import { Route as AppSpecialtyIndexRouteImport } from './routes/app/specialty/index'
import { Route as AppHomeIndexRouteImport } from './routes/app/home/index'
import { Route as AppHistoryIndexRouteImport } from './routes/app/history/index'
import { Route as AppEntryIndexRouteImport } from './routes/app/entry/index'
import { Route as AppComponentIndexRouteImport } from './routes/app/component/index'
import { Route as AppBookOfflineIndexRouteImport } from './routes/app/book-offline/index'
import { Route as AppSpecialtySearchRouteRouteImport } from './routes/app/specialty/search/route'
import { Route as AppSearchcommonLayoutRouteRouteImport } from './routes/app/search/(commonLayout)/route'
import { Route as AppProfileeditLayoutRouteRouteImport } from './routes/app/profile/(editLayout)/route'
import { Route as AppProfilecommonLayoutRouteRouteImport } from './routes/app/profile/(commonLayout)/route'
import { Route as AppPackagecommonLayoutRouteRouteImport } from './routes/app/package/(commonLayout)/route'
import { Route as AppNotificationcommonLayoutRouteRouteImport } from './routes/app/notification/(commonLayout)/route'
import { Route as AppHospitalcommonLayoutRouteRouteImport } from './routes/app/hospital/(commonLayout)/route'
import { Route as AppDoctorcommonLayoutRouteRouteImport } from './routes/app/doctor/(commonLayout)/route'
import { Route as AppBookAppointmentSuccessRouteRouteImport } from './routes/app/book-appointment/success/route'
import { Route as AppBookAppointmentcommonLayoutRouteRouteImport } from './routes/app/book-appointment/(commonLayout)/route'
import { Route as AppAppointmentsdetailLayoutRouteRouteImport } from './routes/app/appointments/(detailLayout)/route'
import { Route as AppAppointmentscommonLayoutRouteRouteImport } from './routes/app/appointments/(commonLayout)/route'
import { Route as AppSearchcommonLayoutIndexRouteImport } from './routes/app/search/(commonLayout)/index'
import { Route as AppProfilecommonLayoutIndexRouteImport } from './routes/app/profile/(commonLayout)/index'
import { Route as AppPackagecommonLayoutIndexRouteImport } from './routes/app/package/(commonLayout)/index'
import { Route as AppNotificationcommonLayoutIndexRouteImport } from './routes/app/notification/(commonLayout)/index'
import { Route as AppHospitalcommonLayoutIndexRouteImport } from './routes/app/hospital/(commonLayout)/index'
import { Route as AppDoctorcommonLayoutIndexRouteImport } from './routes/app/doctor/(commonLayout)/index'
import { Route as AppBookAppointmentcommonLayoutIndexRouteImport } from './routes/app/book-appointment/(commonLayout)/index'
import { Route as AppAppointmentscommonLayoutIndexRouteImport } from './routes/app/appointments/(commonLayout)/index'
import { Route as AppSpecialtySearchSpecialtyIdRouteImport } from './routes/app/specialty/search/$specialtyId'
import { Route as AppProfileeditLayoutMedicalProfilesRouteImport } from './routes/app/profile/(editLayout)/medical-profiles'
import { Route as AppProfileeditLayoutEditRouteImport } from './routes/app/profile/(editLayout)/edit'
import { Route as AppPackagecommonLayoutIdRouteImport } from './routes/app/package/(commonLayout)/$id'
import { Route as AppHospitalcommonLayoutIdRouteImport } from './routes/app/hospital/(commonLayout)/$id'
import { Route as AppDoctorcommonLayoutIdRouteImport } from './routes/app/doctor/(commonLayout)/$id'
import { Route as AppBookAppointmentSuccessAppointmentCodeRouteImport } from './routes/app/book-appointment/success/$appointmentCode'
import { Route as AppAppointmentsdetailLayoutIdRouteImport } from './routes/app/appointments/(detailLayout)/$id'
import { Route as AppPaymentKhqrcommonLayoutRouteRouteImport } from './routes/app/payment/khqr/(commonLayout)/route'
import { Route as AppBookAppointmentPackagecommonLayoutRouteRouteImport } from './routes/app/book-appointment/package/(commonLayout)/route'
import { Route as AppBookAppointmentHospitalcommonLayoutRouteRouteImport } from './routes/app/book-appointment/hospital/(commonLayout)/route'
import { Route as AppBookAppointmentDoctorcommonLayoutRouteRouteImport } from './routes/app/book-appointment/doctor/(commonLayout)/route'
import { Route as AppPaymentKhqrcommonLayoutIndexRouteImport } from './routes/app/payment/khqr/(commonLayout)/index'
import { Route as AppPaymentKhqrcommonLayoutBookingTokenRouteImport } from './routes/app/payment/khqr/(commonLayout)/$bookingToken'
import { Route as AppBookAppointmentPackagecommonLayoutPackageIdRouteImport } from './routes/app/book-appointment/package/(commonLayout)/$packageId'
import { Route as AppBookAppointmentHospitalcommonLayoutHospitalIdRouteImport } from './routes/app/book-appointment/hospital/(commonLayout)/$hospitalId'
import { Route as AppBookAppointmentDoctorcommonLayoutDoctorIdRouteImport } from './routes/app/book-appointment/doctor/(commonLayout)/$doctorId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSpecialtyRouteRoute = AppSpecialtyRouteRouteImport.update({
  id: '/specialty',
  path: '/specialty',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRouteRoute = AppHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRouteRoute = AppHistoryRouteRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookOfflineRouteRoute = AppBookOfflineRouteRouteImport.update({
  id: '/book-offline',
  path: '/book-offline',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSpecialtyIndexRoute = AppSpecialtyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSpecialtyRouteRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHistoryRouteRoute,
} as any)
const AppEntryIndexRoute = AppEntryIndexRouteImport.update({
  id: '/entry/',
  path: '/entry/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentIndexRoute = AppComponentIndexRouteImport.update({
  id: '/component/',
  path: '/component/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookOfflineIndexRoute = AppBookOfflineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookOfflineRouteRoute,
} as any)
const AppSpecialtySearchRouteRoute = AppSpecialtySearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppSpecialtyRouteRoute,
} as any)
const AppSearchcommonLayoutRouteRoute =
  AppSearchcommonLayoutRouteRouteImport.update({
    id: '/search/(commonLayout)',
    path: '/search',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProfileeditLayoutRouteRoute =
  AppProfileeditLayoutRouteRouteImport.update({
    id: '/profile/(editLayout)',
    path: '/profile',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProfilecommonLayoutRouteRoute =
  AppProfilecommonLayoutRouteRouteImport.update({
    id: '/profile/(commonLayout)',
    path: '/profile',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPackagecommonLayoutRouteRoute =
  AppPackagecommonLayoutRouteRouteImport.update({
    id: '/package/(commonLayout)',
    path: '/package',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppNotificationcommonLayoutRouteRoute =
  AppNotificationcommonLayoutRouteRouteImport.update({
    id: '/notification/(commonLayout)',
    path: '/notification',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppHospitalcommonLayoutRouteRoute =
  AppHospitalcommonLayoutRouteRouteImport.update({
    id: '/hospital/(commonLayout)',
    path: '/hospital',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDoctorcommonLayoutRouteRoute =
  AppDoctorcommonLayoutRouteRouteImport.update({
    id: '/doctor/(commonLayout)',
    path: '/doctor',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBookAppointmentSuccessRouteRoute =
  AppBookAppointmentSuccessRouteRouteImport.update({
    id: '/book-appointment/success',
    path: '/book-appointment/success',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBookAppointmentcommonLayoutRouteRoute =
  AppBookAppointmentcommonLayoutRouteRouteImport.update({
    id: '/book-appointment/(commonLayout)',
    path: '/book-appointment',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAppointmentsdetailLayoutRouteRoute =
  AppAppointmentsdetailLayoutRouteRouteImport.update({
    id: '/appointments/(detailLayout)',
    path: '/appointments',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAppointmentscommonLayoutRouteRoute =
  AppAppointmentscommonLayoutRouteRouteImport.update({
    id: '/appointments/(commonLayout)',
    path: '/appointments',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSearchcommonLayoutIndexRoute =
  AppSearchcommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSearchcommonLayoutRouteRoute,
  } as any)
const AppProfilecommonLayoutIndexRoute =
  AppProfilecommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProfilecommonLayoutRouteRoute,
  } as any)
const AppPackagecommonLayoutIndexRoute =
  AppPackagecommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPackagecommonLayoutRouteRoute,
  } as any)
const AppNotificationcommonLayoutIndexRoute =
  AppNotificationcommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppNotificationcommonLayoutRouteRoute,
  } as any)
const AppHospitalcommonLayoutIndexRoute =
  AppHospitalcommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppHospitalcommonLayoutRouteRoute,
  } as any)
const AppDoctorcommonLayoutIndexRoute =
  AppDoctorcommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDoctorcommonLayoutRouteRoute,
  } as any)
const AppBookAppointmentcommonLayoutIndexRoute =
  AppBookAppointmentcommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBookAppointmentcommonLayoutRouteRoute,
  } as any)
const AppAppointmentscommonLayoutIndexRoute =
  AppAppointmentscommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAppointmentscommonLayoutRouteRoute,
  } as any)
const AppSpecialtySearchSpecialtyIdRoute =
  AppSpecialtySearchSpecialtyIdRouteImport.update({
    id: '/$specialtyId',
    path: '/$specialtyId',
    getParentRoute: () => AppSpecialtySearchRouteRoute,
  } as any)
const AppProfileeditLayoutMedicalProfilesRoute =
  AppProfileeditLayoutMedicalProfilesRouteImport.update({
    id: '/medical-profiles',
    path: '/medical-profiles',
    getParentRoute: () => AppProfileeditLayoutRouteRoute,
  } as any)
const AppProfileeditLayoutEditRoute =
  AppProfileeditLayoutEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppProfileeditLayoutRouteRoute,
  } as any)
const AppPackagecommonLayoutIdRoute =
  AppPackagecommonLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppPackagecommonLayoutRouteRoute,
  } as any)
const AppHospitalcommonLayoutIdRoute =
  AppHospitalcommonLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppHospitalcommonLayoutRouteRoute,
  } as any)
const AppDoctorcommonLayoutIdRoute = AppDoctorcommonLayoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDoctorcommonLayoutRouteRoute,
} as any)
const AppBookAppointmentSuccessAppointmentCodeRoute =
  AppBookAppointmentSuccessAppointmentCodeRouteImport.update({
    id: '/$appointmentCode',
    path: '/$appointmentCode',
    getParentRoute: () => AppBookAppointmentSuccessRouteRoute,
  } as any)
const AppAppointmentsdetailLayoutIdRoute =
  AppAppointmentsdetailLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppAppointmentsdetailLayoutRouteRoute,
  } as any)
const AppPaymentKhqrcommonLayoutRouteRoute =
  AppPaymentKhqrcommonLayoutRouteRouteImport.update({
    id: '/payment/khqr/(commonLayout)',
    path: '/payment/khqr',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBookAppointmentPackagecommonLayoutRouteRoute =
  AppBookAppointmentPackagecommonLayoutRouteRouteImport.update({
    id: '/book-appointment/package/(commonLayout)',
    path: '/book-appointment/package',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBookAppointmentHospitalcommonLayoutRouteRoute =
  AppBookAppointmentHospitalcommonLayoutRouteRouteImport.update({
    id: '/book-appointment/hospital/(commonLayout)',
    path: '/book-appointment/hospital',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBookAppointmentDoctorcommonLayoutRouteRoute =
  AppBookAppointmentDoctorcommonLayoutRouteRouteImport.update({
    id: '/book-appointment/doctor/(commonLayout)',
    path: '/book-appointment/doctor',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPaymentKhqrcommonLayoutIndexRoute =
  AppPaymentKhqrcommonLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPaymentKhqrcommonLayoutRouteRoute,
  } as any)
const AppPaymentKhqrcommonLayoutBookingTokenRoute =
  AppPaymentKhqrcommonLayoutBookingTokenRouteImport.update({
    id: '/$bookingToken',
    path: '/$bookingToken',
    getParentRoute: () => AppPaymentKhqrcommonLayoutRouteRoute,
  } as any)
const AppBookAppointmentPackagecommonLayoutPackageIdRoute =
  AppBookAppointmentPackagecommonLayoutPackageIdRouteImport.update({
    id: '/$packageId',
    path: '/$packageId',
    getParentRoute: () => AppBookAppointmentPackagecommonLayoutRouteRoute,
  } as any)
const AppBookAppointmentHospitalcommonLayoutHospitalIdRoute =
  AppBookAppointmentHospitalcommonLayoutHospitalIdRouteImport.update({
    id: '/$hospitalId',
    path: '/$hospitalId',
    getParentRoute: () => AppBookAppointmentHospitalcommonLayoutRouteRoute,
  } as any)
const AppBookAppointmentDoctorcommonLayoutDoctorIdRoute =
  AppBookAppointmentDoctorcommonLayoutDoctorIdRouteImport.update({
    id: '/$doctorId',
    path: '/$doctorId',
    getParentRoute: () => AppBookAppointmentDoctorcommonLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/book-offline': typeof AppBookOfflineRouteRouteWithChildren
  '/app/history': typeof AppHistoryRouteRouteWithChildren
  '/app/home': typeof AppHomeRouteRouteWithChildren
  '/app/specialty': typeof AppSpecialtyRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/appointments': typeof AppAppointmentsdetailLayoutRouteRouteWithChildren
  '/app/book-appointment': typeof AppBookAppointmentcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/success': typeof AppBookAppointmentSuccessRouteRouteWithChildren
  '/app/doctor': typeof AppDoctorcommonLayoutRouteRouteWithChildren
  '/app/hospital': typeof AppHospitalcommonLayoutRouteRouteWithChildren
  '/app/notification': typeof AppNotificationcommonLayoutRouteRouteWithChildren
  '/app/package': typeof AppPackagecommonLayoutRouteRouteWithChildren
  '/app/profile': typeof AppProfileeditLayoutRouteRouteWithChildren
  '/app/search': typeof AppSearchcommonLayoutRouteRouteWithChildren
  '/app/specialty/search': typeof AppSpecialtySearchRouteRouteWithChildren
  '/app/book-offline/': typeof AppBookOfflineIndexRoute
  '/app/component/': typeof AppComponentIndexRoute
  '/app/entry/': typeof AppEntryIndexRoute
  '/app/history/': typeof AppHistoryIndexRoute
  '/app/home/': typeof AppHomeIndexRoute
  '/app/specialty/': typeof AppSpecialtyIndexRoute
  '/app/book-appointment/doctor': typeof AppBookAppointmentDoctorcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/hospital': typeof AppBookAppointmentHospitalcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/package': typeof AppBookAppointmentPackagecommonLayoutRouteRouteWithChildren
  '/app/payment/khqr': typeof AppPaymentKhqrcommonLayoutRouteRouteWithChildren
  '/app/appointments/$id': typeof AppAppointmentsdetailLayoutIdRoute
  '/app/book-appointment/success/$appointmentCode': typeof AppBookAppointmentSuccessAppointmentCodeRoute
  '/app/doctor/$id': typeof AppDoctorcommonLayoutIdRoute
  '/app/hospital/$id': typeof AppHospitalcommonLayoutIdRoute
  '/app/package/$id': typeof AppPackagecommonLayoutIdRoute
  '/app/profile/edit': typeof AppProfileeditLayoutEditRoute
  '/app/profile/medical-profiles': typeof AppProfileeditLayoutMedicalProfilesRoute
  '/app/specialty/search/$specialtyId': typeof AppSpecialtySearchSpecialtyIdRoute
  '/app/appointments/': typeof AppAppointmentscommonLayoutIndexRoute
  '/app/book-appointment/': typeof AppBookAppointmentcommonLayoutIndexRoute
  '/app/doctor/': typeof AppDoctorcommonLayoutIndexRoute
  '/app/hospital/': typeof AppHospitalcommonLayoutIndexRoute
  '/app/notification/': typeof AppNotificationcommonLayoutIndexRoute
  '/app/package/': typeof AppPackagecommonLayoutIndexRoute
  '/app/profile/': typeof AppProfilecommonLayoutIndexRoute
  '/app/search/': typeof AppSearchcommonLayoutIndexRoute
  '/app/book-appointment/doctor/$doctorId': typeof AppBookAppointmentDoctorcommonLayoutDoctorIdRoute
  '/app/book-appointment/hospital/$hospitalId': typeof AppBookAppointmentHospitalcommonLayoutHospitalIdRoute
  '/app/book-appointment/package/$packageId': typeof AppBookAppointmentPackagecommonLayoutPackageIdRoute
  '/app/payment/khqr/$bookingToken': typeof AppPaymentKhqrcommonLayoutBookingTokenRoute
  '/app/payment/khqr/': typeof AppPaymentKhqrcommonLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/appointments': typeof AppAppointmentscommonLayoutIndexRoute
  '/app/book-appointment/success': typeof AppBookAppointmentSuccessRouteRouteWithChildren
  '/app/profile': typeof AppProfilecommonLayoutIndexRoute
  '/app/specialty/search': typeof AppSpecialtySearchRouteRouteWithChildren
  '/app/book-offline': typeof AppBookOfflineIndexRoute
  '/app/component': typeof AppComponentIndexRoute
  '/app/entry': typeof AppEntryIndexRoute
  '/app/history': typeof AppHistoryIndexRoute
  '/app/home': typeof AppHomeIndexRoute
  '/app/specialty': typeof AppSpecialtyIndexRoute
  '/app/book-appointment/doctor': typeof AppBookAppointmentDoctorcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/hospital': typeof AppBookAppointmentHospitalcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/package': typeof AppBookAppointmentPackagecommonLayoutRouteRouteWithChildren
  '/app/appointments/$id': typeof AppAppointmentsdetailLayoutIdRoute
  '/app/book-appointment/success/$appointmentCode': typeof AppBookAppointmentSuccessAppointmentCodeRoute
  '/app/doctor/$id': typeof AppDoctorcommonLayoutIdRoute
  '/app/hospital/$id': typeof AppHospitalcommonLayoutIdRoute
  '/app/package/$id': typeof AppPackagecommonLayoutIdRoute
  '/app/profile/edit': typeof AppProfileeditLayoutEditRoute
  '/app/profile/medical-profiles': typeof AppProfileeditLayoutMedicalProfilesRoute
  '/app/specialty/search/$specialtyId': typeof AppSpecialtySearchSpecialtyIdRoute
  '/app/book-appointment': typeof AppBookAppointmentcommonLayoutIndexRoute
  '/app/doctor': typeof AppDoctorcommonLayoutIndexRoute
  '/app/hospital': typeof AppHospitalcommonLayoutIndexRoute
  '/app/notification': typeof AppNotificationcommonLayoutIndexRoute
  '/app/package': typeof AppPackagecommonLayoutIndexRoute
  '/app/search': typeof AppSearchcommonLayoutIndexRoute
  '/app/book-appointment/doctor/$doctorId': typeof AppBookAppointmentDoctorcommonLayoutDoctorIdRoute
  '/app/book-appointment/hospital/$hospitalId': typeof AppBookAppointmentHospitalcommonLayoutHospitalIdRoute
  '/app/book-appointment/package/$packageId': typeof AppBookAppointmentPackagecommonLayoutPackageIdRoute
  '/app/payment/khqr/$bookingToken': typeof AppPaymentKhqrcommonLayoutBookingTokenRoute
  '/app/payment/khqr': typeof AppPaymentKhqrcommonLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/book-offline': typeof AppBookOfflineRouteRouteWithChildren
  '/app/history': typeof AppHistoryRouteRouteWithChildren
  '/app/home': typeof AppHomeRouteRouteWithChildren
  '/app/specialty': typeof AppSpecialtyRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/appointments/(commonLayout)': typeof AppAppointmentscommonLayoutRouteRouteWithChildren
  '/app/appointments/(detailLayout)': typeof AppAppointmentsdetailLayoutRouteRouteWithChildren
  '/app/book-appointment/(commonLayout)': typeof AppBookAppointmentcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/success': typeof AppBookAppointmentSuccessRouteRouteWithChildren
  '/app/doctor/(commonLayout)': typeof AppDoctorcommonLayoutRouteRouteWithChildren
  '/app/hospital/(commonLayout)': typeof AppHospitalcommonLayoutRouteRouteWithChildren
  '/app/notification/(commonLayout)': typeof AppNotificationcommonLayoutRouteRouteWithChildren
  '/app/package/(commonLayout)': typeof AppPackagecommonLayoutRouteRouteWithChildren
  '/app/profile/(commonLayout)': typeof AppProfilecommonLayoutRouteRouteWithChildren
  '/app/profile/(editLayout)': typeof AppProfileeditLayoutRouteRouteWithChildren
  '/app/search/(commonLayout)': typeof AppSearchcommonLayoutRouteRouteWithChildren
  '/app/specialty/search': typeof AppSpecialtySearchRouteRouteWithChildren
  '/app/book-offline/': typeof AppBookOfflineIndexRoute
  '/app/component/': typeof AppComponentIndexRoute
  '/app/entry/': typeof AppEntryIndexRoute
  '/app/history/': typeof AppHistoryIndexRoute
  '/app/home/': typeof AppHomeIndexRoute
  '/app/specialty/': typeof AppSpecialtyIndexRoute
  '/app/book-appointment/doctor/(commonLayout)': typeof AppBookAppointmentDoctorcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/hospital/(commonLayout)': typeof AppBookAppointmentHospitalcommonLayoutRouteRouteWithChildren
  '/app/book-appointment/package/(commonLayout)': typeof AppBookAppointmentPackagecommonLayoutRouteRouteWithChildren
  '/app/payment/khqr/(commonLayout)': typeof AppPaymentKhqrcommonLayoutRouteRouteWithChildren
  '/app/appointments/(detailLayout)/$id': typeof AppAppointmentsdetailLayoutIdRoute
  '/app/book-appointment/success/$appointmentCode': typeof AppBookAppointmentSuccessAppointmentCodeRoute
  '/app/doctor/(commonLayout)/$id': typeof AppDoctorcommonLayoutIdRoute
  '/app/hospital/(commonLayout)/$id': typeof AppHospitalcommonLayoutIdRoute
  '/app/package/(commonLayout)/$id': typeof AppPackagecommonLayoutIdRoute
  '/app/profile/(editLayout)/edit': typeof AppProfileeditLayoutEditRoute
  '/app/profile/(editLayout)/medical-profiles': typeof AppProfileeditLayoutMedicalProfilesRoute
  '/app/specialty/search/$specialtyId': typeof AppSpecialtySearchSpecialtyIdRoute
  '/app/appointments/(commonLayout)/': typeof AppAppointmentscommonLayoutIndexRoute
  '/app/book-appointment/(commonLayout)/': typeof AppBookAppointmentcommonLayoutIndexRoute
  '/app/doctor/(commonLayout)/': typeof AppDoctorcommonLayoutIndexRoute
  '/app/hospital/(commonLayout)/': typeof AppHospitalcommonLayoutIndexRoute
  '/app/notification/(commonLayout)/': typeof AppNotificationcommonLayoutIndexRoute
  '/app/package/(commonLayout)/': typeof AppPackagecommonLayoutIndexRoute
  '/app/profile/(commonLayout)/': typeof AppProfilecommonLayoutIndexRoute
  '/app/search/(commonLayout)/': typeof AppSearchcommonLayoutIndexRoute
  '/app/book-appointment/doctor/(commonLayout)/$doctorId': typeof AppBookAppointmentDoctorcommonLayoutDoctorIdRoute
  '/app/book-appointment/hospital/(commonLayout)/$hospitalId': typeof AppBookAppointmentHospitalcommonLayoutHospitalIdRoute
  '/app/book-appointment/package/(commonLayout)/$packageId': typeof AppBookAppointmentPackagecommonLayoutPackageIdRoute
  '/app/payment/khqr/(commonLayout)/$bookingToken': typeof AppPaymentKhqrcommonLayoutBookingTokenRoute
  '/app/payment/khqr/(commonLayout)/': typeof AppPaymentKhqrcommonLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/book-offline'
    | '/app/history'
    | '/app/home'
    | '/app/specialty'
    | '/app/'
    | '/app/appointments'
    | '/app/book-appointment'
    | '/app/book-appointment/success'
    | '/app/doctor'
    | '/app/hospital'
    | '/app/notification'
    | '/app/package'
    | '/app/profile'
    | '/app/search'
    | '/app/specialty/search'
    | '/app/book-offline/'
    | '/app/component/'
    | '/app/entry/'
    | '/app/history/'
    | '/app/home/'
    | '/app/specialty/'
    | '/app/book-appointment/doctor'
    | '/app/book-appointment/hospital'
    | '/app/book-appointment/package'
    | '/app/payment/khqr'
    | '/app/appointments/$id'
    | '/app/book-appointment/success/$appointmentCode'
    | '/app/doctor/$id'
    | '/app/hospital/$id'
    | '/app/package/$id'
    | '/app/profile/edit'
    | '/app/profile/medical-profiles'
    | '/app/specialty/search/$specialtyId'
    | '/app/appointments/'
    | '/app/book-appointment/'
    | '/app/doctor/'
    | '/app/hospital/'
    | '/app/notification/'
    | '/app/package/'
    | '/app/profile/'
    | '/app/search/'
    | '/app/book-appointment/doctor/$doctorId'
    | '/app/book-appointment/hospital/$hospitalId'
    | '/app/book-appointment/package/$packageId'
    | '/app/payment/khqr/$bookingToken'
    | '/app/payment/khqr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/appointments'
    | '/app/book-appointment/success'
    | '/app/profile'
    | '/app/specialty/search'
    | '/app/book-offline'
    | '/app/component'
    | '/app/entry'
    | '/app/history'
    | '/app/home'
    | '/app/specialty'
    | '/app/book-appointment/doctor'
    | '/app/book-appointment/hospital'
    | '/app/book-appointment/package'
    | '/app/appointments/$id'
    | '/app/book-appointment/success/$appointmentCode'
    | '/app/doctor/$id'
    | '/app/hospital/$id'
    | '/app/package/$id'
    | '/app/profile/edit'
    | '/app/profile/medical-profiles'
    | '/app/specialty/search/$specialtyId'
    | '/app/book-appointment'
    | '/app/doctor'
    | '/app/hospital'
    | '/app/notification'
    | '/app/package'
    | '/app/search'
    | '/app/book-appointment/doctor/$doctorId'
    | '/app/book-appointment/hospital/$hospitalId'
    | '/app/book-appointment/package/$packageId'
    | '/app/payment/khqr/$bookingToken'
    | '/app/payment/khqr'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/book-offline'
    | '/app/history'
    | '/app/home'
    | '/app/specialty'
    | '/app/'
    | '/app/appointments/(commonLayout)'
    | '/app/appointments/(detailLayout)'
    | '/app/book-appointment/(commonLayout)'
    | '/app/book-appointment/success'
    | '/app/doctor/(commonLayout)'
    | '/app/hospital/(commonLayout)'
    | '/app/notification/(commonLayout)'
    | '/app/package/(commonLayout)'
    | '/app/profile/(commonLayout)'
    | '/app/profile/(editLayout)'
    | '/app/search/(commonLayout)'
    | '/app/specialty/search'
    | '/app/book-offline/'
    | '/app/component/'
    | '/app/entry/'
    | '/app/history/'
    | '/app/home/'
    | '/app/specialty/'
    | '/app/book-appointment/doctor/(commonLayout)'
    | '/app/book-appointment/hospital/(commonLayout)'
    | '/app/book-appointment/package/(commonLayout)'
    | '/app/payment/khqr/(commonLayout)'
    | '/app/appointments/(detailLayout)/$id'
    | '/app/book-appointment/success/$appointmentCode'
    | '/app/doctor/(commonLayout)/$id'
    | '/app/hospital/(commonLayout)/$id'
    | '/app/package/(commonLayout)/$id'
    | '/app/profile/(editLayout)/edit'
    | '/app/profile/(editLayout)/medical-profiles'
    | '/app/specialty/search/$specialtyId'
    | '/app/appointments/(commonLayout)/'
    | '/app/book-appointment/(commonLayout)/'
    | '/app/doctor/(commonLayout)/'
    | '/app/hospital/(commonLayout)/'
    | '/app/notification/(commonLayout)/'
    | '/app/package/(commonLayout)/'
    | '/app/profile/(commonLayout)/'
    | '/app/search/(commonLayout)/'
    | '/app/book-appointment/doctor/(commonLayout)/$doctorId'
    | '/app/book-appointment/hospital/(commonLayout)/$hospitalId'
    | '/app/book-appointment/package/(commonLayout)/$packageId'
    | '/app/payment/khqr/(commonLayout)/$bookingToken'
    | '/app/payment/khqr/(commonLayout)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/specialty': {
      id: '/app/specialty'
      path: '/specialty'
      fullPath: '/app/specialty'
      preLoaderRoute: typeof AppSpecialtyRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-offline': {
      id: '/app/book-offline'
      path: '/book-offline'
      fullPath: '/app/book-offline'
      preLoaderRoute: typeof AppBookOfflineRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/specialty/': {
      id: '/app/specialty/'
      path: '/'
      fullPath: '/app/specialty/'
      preLoaderRoute: typeof AppSpecialtyIndexRouteImport
      parentRoute: typeof AppSpecialtyRouteRoute
    }
    '/app/home/': {
      id: '/app/home/'
      path: '/'
      fullPath: '/app/home/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/app/history/': {
      id: '/app/history/'
      path: '/'
      fullPath: '/app/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppHistoryRouteRoute
    }
    '/app/entry/': {
      id: '/app/entry/'
      path: '/entry'
      fullPath: '/app/entry/'
      preLoaderRoute: typeof AppEntryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/component/': {
      id: '/app/component/'
      path: '/component'
      fullPath: '/app/component/'
      preLoaderRoute: typeof AppComponentIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-offline/': {
      id: '/app/book-offline/'
      path: '/'
      fullPath: '/app/book-offline/'
      preLoaderRoute: typeof AppBookOfflineIndexRouteImport
      parentRoute: typeof AppBookOfflineRouteRoute
    }
    '/app/specialty/search': {
      id: '/app/specialty/search'
      path: '/search'
      fullPath: '/app/specialty/search'
      preLoaderRoute: typeof AppSpecialtySearchRouteRouteImport
      parentRoute: typeof AppSpecialtyRouteRoute
    }
    '/app/search/(commonLayout)': {
      id: '/app/search/(commonLayout)'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/(editLayout)': {
      id: '/app/profile/(editLayout)'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileeditLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/(commonLayout)': {
      id: '/app/profile/(commonLayout)'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfilecommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/package/(commonLayout)': {
      id: '/app/package/(commonLayout)'
      path: '/package'
      fullPath: '/app/package'
      preLoaderRoute: typeof AppPackagecommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notification/(commonLayout)': {
      id: '/app/notification/(commonLayout)'
      path: '/notification'
      fullPath: '/app/notification'
      preLoaderRoute: typeof AppNotificationcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hospital/(commonLayout)': {
      id: '/app/hospital/(commonLayout)'
      path: '/hospital'
      fullPath: '/app/hospital'
      preLoaderRoute: typeof AppHospitalcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/doctor/(commonLayout)': {
      id: '/app/doctor/(commonLayout)'
      path: '/doctor'
      fullPath: '/app/doctor'
      preLoaderRoute: typeof AppDoctorcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-appointment/success': {
      id: '/app/book-appointment/success'
      path: '/book-appointment/success'
      fullPath: '/app/book-appointment/success'
      preLoaderRoute: typeof AppBookAppointmentSuccessRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-appointment/(commonLayout)': {
      id: '/app/book-appointment/(commonLayout)'
      path: '/book-appointment'
      fullPath: '/app/book-appointment'
      preLoaderRoute: typeof AppBookAppointmentcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/appointments/(detailLayout)': {
      id: '/app/appointments/(detailLayout)'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsdetailLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/appointments/(commonLayout)': {
      id: '/app/appointments/(commonLayout)'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentscommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/search/(commonLayout)/': {
      id: '/app/search/(commonLayout)/'
      path: '/'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppSearchcommonLayoutIndexRouteImport
      parentRoute: typeof AppSearchcommonLayoutRouteRoute
    }
    '/app/profile/(commonLayout)/': {
      id: '/app/profile/(commonLayout)/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfilecommonLayoutIndexRouteImport
      parentRoute: typeof AppProfilecommonLayoutRouteRoute
    }
    '/app/package/(commonLayout)/': {
      id: '/app/package/(commonLayout)/'
      path: '/'
      fullPath: '/app/package/'
      preLoaderRoute: typeof AppPackagecommonLayoutIndexRouteImport
      parentRoute: typeof AppPackagecommonLayoutRouteRoute
    }
    '/app/notification/(commonLayout)/': {
      id: '/app/notification/(commonLayout)/'
      path: '/'
      fullPath: '/app/notification/'
      preLoaderRoute: typeof AppNotificationcommonLayoutIndexRouteImport
      parentRoute: typeof AppNotificationcommonLayoutRouteRoute
    }
    '/app/hospital/(commonLayout)/': {
      id: '/app/hospital/(commonLayout)/'
      path: '/'
      fullPath: '/app/hospital/'
      preLoaderRoute: typeof AppHospitalcommonLayoutIndexRouteImport
      parentRoute: typeof AppHospitalcommonLayoutRouteRoute
    }
    '/app/doctor/(commonLayout)/': {
      id: '/app/doctor/(commonLayout)/'
      path: '/'
      fullPath: '/app/doctor/'
      preLoaderRoute: typeof AppDoctorcommonLayoutIndexRouteImport
      parentRoute: typeof AppDoctorcommonLayoutRouteRoute
    }
    '/app/book-appointment/(commonLayout)/': {
      id: '/app/book-appointment/(commonLayout)/'
      path: '/'
      fullPath: '/app/book-appointment/'
      preLoaderRoute: typeof AppBookAppointmentcommonLayoutIndexRouteImport
      parentRoute: typeof AppBookAppointmentcommonLayoutRouteRoute
    }
    '/app/appointments/(commonLayout)/': {
      id: '/app/appointments/(commonLayout)/'
      path: '/'
      fullPath: '/app/appointments/'
      preLoaderRoute: typeof AppAppointmentscommonLayoutIndexRouteImport
      parentRoute: typeof AppAppointmentscommonLayoutRouteRoute
    }
    '/app/specialty/search/$specialtyId': {
      id: '/app/specialty/search/$specialtyId'
      path: '/$specialtyId'
      fullPath: '/app/specialty/search/$specialtyId'
      preLoaderRoute: typeof AppSpecialtySearchSpecialtyIdRouteImport
      parentRoute: typeof AppSpecialtySearchRouteRoute
    }
    '/app/profile/(editLayout)/medical-profiles': {
      id: '/app/profile/(editLayout)/medical-profiles'
      path: '/medical-profiles'
      fullPath: '/app/profile/medical-profiles'
      preLoaderRoute: typeof AppProfileeditLayoutMedicalProfilesRouteImport
      parentRoute: typeof AppProfileeditLayoutRouteRoute
    }
    '/app/profile/(editLayout)/edit': {
      id: '/app/profile/(editLayout)/edit'
      path: '/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileeditLayoutEditRouteImport
      parentRoute: typeof AppProfileeditLayoutRouteRoute
    }
    '/app/package/(commonLayout)/$id': {
      id: '/app/package/(commonLayout)/$id'
      path: '/$id'
      fullPath: '/app/package/$id'
      preLoaderRoute: typeof AppPackagecommonLayoutIdRouteImport
      parentRoute: typeof AppPackagecommonLayoutRouteRoute
    }
    '/app/hospital/(commonLayout)/$id': {
      id: '/app/hospital/(commonLayout)/$id'
      path: '/$id'
      fullPath: '/app/hospital/$id'
      preLoaderRoute: typeof AppHospitalcommonLayoutIdRouteImport
      parentRoute: typeof AppHospitalcommonLayoutRouteRoute
    }
    '/app/doctor/(commonLayout)/$id': {
      id: '/app/doctor/(commonLayout)/$id'
      path: '/$id'
      fullPath: '/app/doctor/$id'
      preLoaderRoute: typeof AppDoctorcommonLayoutIdRouteImport
      parentRoute: typeof AppDoctorcommonLayoutRouteRoute
    }
    '/app/book-appointment/success/$appointmentCode': {
      id: '/app/book-appointment/success/$appointmentCode'
      path: '/$appointmentCode'
      fullPath: '/app/book-appointment/success/$appointmentCode'
      preLoaderRoute: typeof AppBookAppointmentSuccessAppointmentCodeRouteImport
      parentRoute: typeof AppBookAppointmentSuccessRouteRoute
    }
    '/app/appointments/(detailLayout)/$id': {
      id: '/app/appointments/(detailLayout)/$id'
      path: '/$id'
      fullPath: '/app/appointments/$id'
      preLoaderRoute: typeof AppAppointmentsdetailLayoutIdRouteImport
      parentRoute: typeof AppAppointmentsdetailLayoutRouteRoute
    }
    '/app/payment/khqr/(commonLayout)': {
      id: '/app/payment/khqr/(commonLayout)'
      path: '/payment/khqr'
      fullPath: '/app/payment/khqr'
      preLoaderRoute: typeof AppPaymentKhqrcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-appointment/package/(commonLayout)': {
      id: '/app/book-appointment/package/(commonLayout)'
      path: '/book-appointment/package'
      fullPath: '/app/book-appointment/package'
      preLoaderRoute: typeof AppBookAppointmentPackagecommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-appointment/hospital/(commonLayout)': {
      id: '/app/book-appointment/hospital/(commonLayout)'
      path: '/book-appointment/hospital'
      fullPath: '/app/book-appointment/hospital'
      preLoaderRoute: typeof AppBookAppointmentHospitalcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book-appointment/doctor/(commonLayout)': {
      id: '/app/book-appointment/doctor/(commonLayout)'
      path: '/book-appointment/doctor'
      fullPath: '/app/book-appointment/doctor'
      preLoaderRoute: typeof AppBookAppointmentDoctorcommonLayoutRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payment/khqr/(commonLayout)/': {
      id: '/app/payment/khqr/(commonLayout)/'
      path: '/'
      fullPath: '/app/payment/khqr/'
      preLoaderRoute: typeof AppPaymentKhqrcommonLayoutIndexRouteImport
      parentRoute: typeof AppPaymentKhqrcommonLayoutRouteRoute
    }
    '/app/payment/khqr/(commonLayout)/$bookingToken': {
      id: '/app/payment/khqr/(commonLayout)/$bookingToken'
      path: '/$bookingToken'
      fullPath: '/app/payment/khqr/$bookingToken'
      preLoaderRoute: typeof AppPaymentKhqrcommonLayoutBookingTokenRouteImport
      parentRoute: typeof AppPaymentKhqrcommonLayoutRouteRoute
    }
    '/app/book-appointment/package/(commonLayout)/$packageId': {
      id: '/app/book-appointment/package/(commonLayout)/$packageId'
      path: '/$packageId'
      fullPath: '/app/book-appointment/package/$packageId'
      preLoaderRoute: typeof AppBookAppointmentPackagecommonLayoutPackageIdRouteImport
      parentRoute: typeof AppBookAppointmentPackagecommonLayoutRouteRoute
    }
    '/app/book-appointment/hospital/(commonLayout)/$hospitalId': {
      id: '/app/book-appointment/hospital/(commonLayout)/$hospitalId'
      path: '/$hospitalId'
      fullPath: '/app/book-appointment/hospital/$hospitalId'
      preLoaderRoute: typeof AppBookAppointmentHospitalcommonLayoutHospitalIdRouteImport
      parentRoute: typeof AppBookAppointmentHospitalcommonLayoutRouteRoute
    }
    '/app/book-appointment/doctor/(commonLayout)/$doctorId': {
      id: '/app/book-appointment/doctor/(commonLayout)/$doctorId'
      path: '/$doctorId'
      fullPath: '/app/book-appointment/doctor/$doctorId'
      preLoaderRoute: typeof AppBookAppointmentDoctorcommonLayoutDoctorIdRouteImport
      parentRoute: typeof AppBookAppointmentDoctorcommonLayoutRouteRoute
    }
  }
}

interface AppBookOfflineRouteRouteChildren {
  AppBookOfflineIndexRoute: typeof AppBookOfflineIndexRoute
}

const AppBookOfflineRouteRouteChildren: AppBookOfflineRouteRouteChildren = {
  AppBookOfflineIndexRoute: AppBookOfflineIndexRoute,
}

const AppBookOfflineRouteRouteWithChildren =
  AppBookOfflineRouteRoute._addFileChildren(AppBookOfflineRouteRouteChildren)

interface AppHistoryRouteRouteChildren {
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
}

const AppHistoryRouteRouteChildren: AppHistoryRouteRouteChildren = {
  AppHistoryIndexRoute: AppHistoryIndexRoute,
}

const AppHistoryRouteRouteWithChildren = AppHistoryRouteRoute._addFileChildren(
  AppHistoryRouteRouteChildren,
)

interface AppHomeRouteRouteChildren {
  AppHomeIndexRoute: typeof AppHomeIndexRoute
}

const AppHomeRouteRouteChildren: AppHomeRouteRouteChildren = {
  AppHomeIndexRoute: AppHomeIndexRoute,
}

const AppHomeRouteRouteWithChildren = AppHomeRouteRoute._addFileChildren(
  AppHomeRouteRouteChildren,
)

interface AppSpecialtySearchRouteRouteChildren {
  AppSpecialtySearchSpecialtyIdRoute: typeof AppSpecialtySearchSpecialtyIdRoute
}

const AppSpecialtySearchRouteRouteChildren: AppSpecialtySearchRouteRouteChildren =
  {
    AppSpecialtySearchSpecialtyIdRoute: AppSpecialtySearchSpecialtyIdRoute,
  }

const AppSpecialtySearchRouteRouteWithChildren =
  AppSpecialtySearchRouteRoute._addFileChildren(
    AppSpecialtySearchRouteRouteChildren,
  )

interface AppSpecialtyRouteRouteChildren {
  AppSpecialtySearchRouteRoute: typeof AppSpecialtySearchRouteRouteWithChildren
  AppSpecialtyIndexRoute: typeof AppSpecialtyIndexRoute
}

const AppSpecialtyRouteRouteChildren: AppSpecialtyRouteRouteChildren = {
  AppSpecialtySearchRouteRoute: AppSpecialtySearchRouteRouteWithChildren,
  AppSpecialtyIndexRoute: AppSpecialtyIndexRoute,
}

const AppSpecialtyRouteRouteWithChildren =
  AppSpecialtyRouteRoute._addFileChildren(AppSpecialtyRouteRouteChildren)

interface AppAppointmentscommonLayoutRouteRouteChildren {
  AppAppointmentscommonLayoutIndexRoute: typeof AppAppointmentscommonLayoutIndexRoute
}

const AppAppointmentscommonLayoutRouteRouteChildren: AppAppointmentscommonLayoutRouteRouteChildren =
  {
    AppAppointmentscommonLayoutIndexRoute:
      AppAppointmentscommonLayoutIndexRoute,
  }

const AppAppointmentscommonLayoutRouteRouteWithChildren =
  AppAppointmentscommonLayoutRouteRoute._addFileChildren(
    AppAppointmentscommonLayoutRouteRouteChildren,
  )

interface AppAppointmentsdetailLayoutRouteRouteChildren {
  AppAppointmentsdetailLayoutIdRoute: typeof AppAppointmentsdetailLayoutIdRoute
}

const AppAppointmentsdetailLayoutRouteRouteChildren: AppAppointmentsdetailLayoutRouteRouteChildren =
  {
    AppAppointmentsdetailLayoutIdRoute: AppAppointmentsdetailLayoutIdRoute,
  }

const AppAppointmentsdetailLayoutRouteRouteWithChildren =
  AppAppointmentsdetailLayoutRouteRoute._addFileChildren(
    AppAppointmentsdetailLayoutRouteRouteChildren,
  )

interface AppBookAppointmentcommonLayoutRouteRouteChildren {
  AppBookAppointmentcommonLayoutIndexRoute: typeof AppBookAppointmentcommonLayoutIndexRoute
}

const AppBookAppointmentcommonLayoutRouteRouteChildren: AppBookAppointmentcommonLayoutRouteRouteChildren =
  {
    AppBookAppointmentcommonLayoutIndexRoute:
      AppBookAppointmentcommonLayoutIndexRoute,
  }

const AppBookAppointmentcommonLayoutRouteRouteWithChildren =
  AppBookAppointmentcommonLayoutRouteRoute._addFileChildren(
    AppBookAppointmentcommonLayoutRouteRouteChildren,
  )

interface AppBookAppointmentSuccessRouteRouteChildren {
  AppBookAppointmentSuccessAppointmentCodeRoute: typeof AppBookAppointmentSuccessAppointmentCodeRoute
}

const AppBookAppointmentSuccessRouteRouteChildren: AppBookAppointmentSuccessRouteRouteChildren =
  {
    AppBookAppointmentSuccessAppointmentCodeRoute:
      AppBookAppointmentSuccessAppointmentCodeRoute,
  }

const AppBookAppointmentSuccessRouteRouteWithChildren =
  AppBookAppointmentSuccessRouteRoute._addFileChildren(
    AppBookAppointmentSuccessRouteRouteChildren,
  )

interface AppDoctorcommonLayoutRouteRouteChildren {
  AppDoctorcommonLayoutIdRoute: typeof AppDoctorcommonLayoutIdRoute
  AppDoctorcommonLayoutIndexRoute: typeof AppDoctorcommonLayoutIndexRoute
}

const AppDoctorcommonLayoutRouteRouteChildren: AppDoctorcommonLayoutRouteRouteChildren =
  {
    AppDoctorcommonLayoutIdRoute: AppDoctorcommonLayoutIdRoute,
    AppDoctorcommonLayoutIndexRoute: AppDoctorcommonLayoutIndexRoute,
  }

const AppDoctorcommonLayoutRouteRouteWithChildren =
  AppDoctorcommonLayoutRouteRoute._addFileChildren(
    AppDoctorcommonLayoutRouteRouteChildren,
  )

interface AppHospitalcommonLayoutRouteRouteChildren {
  AppHospitalcommonLayoutIdRoute: typeof AppHospitalcommonLayoutIdRoute
  AppHospitalcommonLayoutIndexRoute: typeof AppHospitalcommonLayoutIndexRoute
}

const AppHospitalcommonLayoutRouteRouteChildren: AppHospitalcommonLayoutRouteRouteChildren =
  {
    AppHospitalcommonLayoutIdRoute: AppHospitalcommonLayoutIdRoute,
    AppHospitalcommonLayoutIndexRoute: AppHospitalcommonLayoutIndexRoute,
  }

const AppHospitalcommonLayoutRouteRouteWithChildren =
  AppHospitalcommonLayoutRouteRoute._addFileChildren(
    AppHospitalcommonLayoutRouteRouteChildren,
  )

interface AppNotificationcommonLayoutRouteRouteChildren {
  AppNotificationcommonLayoutIndexRoute: typeof AppNotificationcommonLayoutIndexRoute
}

const AppNotificationcommonLayoutRouteRouteChildren: AppNotificationcommonLayoutRouteRouteChildren =
  {
    AppNotificationcommonLayoutIndexRoute:
      AppNotificationcommonLayoutIndexRoute,
  }

const AppNotificationcommonLayoutRouteRouteWithChildren =
  AppNotificationcommonLayoutRouteRoute._addFileChildren(
    AppNotificationcommonLayoutRouteRouteChildren,
  )

interface AppPackagecommonLayoutRouteRouteChildren {
  AppPackagecommonLayoutIdRoute: typeof AppPackagecommonLayoutIdRoute
  AppPackagecommonLayoutIndexRoute: typeof AppPackagecommonLayoutIndexRoute
}

const AppPackagecommonLayoutRouteRouteChildren: AppPackagecommonLayoutRouteRouteChildren =
  {
    AppPackagecommonLayoutIdRoute: AppPackagecommonLayoutIdRoute,
    AppPackagecommonLayoutIndexRoute: AppPackagecommonLayoutIndexRoute,
  }

const AppPackagecommonLayoutRouteRouteWithChildren =
  AppPackagecommonLayoutRouteRoute._addFileChildren(
    AppPackagecommonLayoutRouteRouteChildren,
  )

interface AppProfilecommonLayoutRouteRouteChildren {
  AppProfilecommonLayoutIndexRoute: typeof AppProfilecommonLayoutIndexRoute
}

const AppProfilecommonLayoutRouteRouteChildren: AppProfilecommonLayoutRouteRouteChildren =
  {
    AppProfilecommonLayoutIndexRoute: AppProfilecommonLayoutIndexRoute,
  }

const AppProfilecommonLayoutRouteRouteWithChildren =
  AppProfilecommonLayoutRouteRoute._addFileChildren(
    AppProfilecommonLayoutRouteRouteChildren,
  )

interface AppProfileeditLayoutRouteRouteChildren {
  AppProfileeditLayoutEditRoute: typeof AppProfileeditLayoutEditRoute
  AppProfileeditLayoutMedicalProfilesRoute: typeof AppProfileeditLayoutMedicalProfilesRoute
}

const AppProfileeditLayoutRouteRouteChildren: AppProfileeditLayoutRouteRouteChildren =
  {
    AppProfileeditLayoutEditRoute: AppProfileeditLayoutEditRoute,
    AppProfileeditLayoutMedicalProfilesRoute:
      AppProfileeditLayoutMedicalProfilesRoute,
  }

const AppProfileeditLayoutRouteRouteWithChildren =
  AppProfileeditLayoutRouteRoute._addFileChildren(
    AppProfileeditLayoutRouteRouteChildren,
  )

interface AppSearchcommonLayoutRouteRouteChildren {
  AppSearchcommonLayoutIndexRoute: typeof AppSearchcommonLayoutIndexRoute
}

const AppSearchcommonLayoutRouteRouteChildren: AppSearchcommonLayoutRouteRouteChildren =
  {
    AppSearchcommonLayoutIndexRoute: AppSearchcommonLayoutIndexRoute,
  }

const AppSearchcommonLayoutRouteRouteWithChildren =
  AppSearchcommonLayoutRouteRoute._addFileChildren(
    AppSearchcommonLayoutRouteRouteChildren,
  )

interface AppBookAppointmentDoctorcommonLayoutRouteRouteChildren {
  AppBookAppointmentDoctorcommonLayoutDoctorIdRoute: typeof AppBookAppointmentDoctorcommonLayoutDoctorIdRoute
}

const AppBookAppointmentDoctorcommonLayoutRouteRouteChildren: AppBookAppointmentDoctorcommonLayoutRouteRouteChildren =
  {
    AppBookAppointmentDoctorcommonLayoutDoctorIdRoute:
      AppBookAppointmentDoctorcommonLayoutDoctorIdRoute,
  }

const AppBookAppointmentDoctorcommonLayoutRouteRouteWithChildren =
  AppBookAppointmentDoctorcommonLayoutRouteRoute._addFileChildren(
    AppBookAppointmentDoctorcommonLayoutRouteRouteChildren,
  )

interface AppBookAppointmentHospitalcommonLayoutRouteRouteChildren {
  AppBookAppointmentHospitalcommonLayoutHospitalIdRoute: typeof AppBookAppointmentHospitalcommonLayoutHospitalIdRoute
}

const AppBookAppointmentHospitalcommonLayoutRouteRouteChildren: AppBookAppointmentHospitalcommonLayoutRouteRouteChildren =
  {
    AppBookAppointmentHospitalcommonLayoutHospitalIdRoute:
      AppBookAppointmentHospitalcommonLayoutHospitalIdRoute,
  }

const AppBookAppointmentHospitalcommonLayoutRouteRouteWithChildren =
  AppBookAppointmentHospitalcommonLayoutRouteRoute._addFileChildren(
    AppBookAppointmentHospitalcommonLayoutRouteRouteChildren,
  )

interface AppBookAppointmentPackagecommonLayoutRouteRouteChildren {
  AppBookAppointmentPackagecommonLayoutPackageIdRoute: typeof AppBookAppointmentPackagecommonLayoutPackageIdRoute
}

const AppBookAppointmentPackagecommonLayoutRouteRouteChildren: AppBookAppointmentPackagecommonLayoutRouteRouteChildren =
  {
    AppBookAppointmentPackagecommonLayoutPackageIdRoute:
      AppBookAppointmentPackagecommonLayoutPackageIdRoute,
  }

const AppBookAppointmentPackagecommonLayoutRouteRouteWithChildren =
  AppBookAppointmentPackagecommonLayoutRouteRoute._addFileChildren(
    AppBookAppointmentPackagecommonLayoutRouteRouteChildren,
  )

interface AppPaymentKhqrcommonLayoutRouteRouteChildren {
  AppPaymentKhqrcommonLayoutBookingTokenRoute: typeof AppPaymentKhqrcommonLayoutBookingTokenRoute
  AppPaymentKhqrcommonLayoutIndexRoute: typeof AppPaymentKhqrcommonLayoutIndexRoute
}

const AppPaymentKhqrcommonLayoutRouteRouteChildren: AppPaymentKhqrcommonLayoutRouteRouteChildren =
  {
    AppPaymentKhqrcommonLayoutBookingTokenRoute:
      AppPaymentKhqrcommonLayoutBookingTokenRoute,
    AppPaymentKhqrcommonLayoutIndexRoute: AppPaymentKhqrcommonLayoutIndexRoute,
  }

const AppPaymentKhqrcommonLayoutRouteRouteWithChildren =
  AppPaymentKhqrcommonLayoutRouteRoute._addFileChildren(
    AppPaymentKhqrcommonLayoutRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppBookOfflineRouteRoute: typeof AppBookOfflineRouteRouteWithChildren
  AppHistoryRouteRoute: typeof AppHistoryRouteRouteWithChildren
  AppHomeRouteRoute: typeof AppHomeRouteRouteWithChildren
  AppSpecialtyRouteRoute: typeof AppSpecialtyRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAppointmentscommonLayoutRouteRoute: typeof AppAppointmentscommonLayoutRouteRouteWithChildren
  AppAppointmentsdetailLayoutRouteRoute: typeof AppAppointmentsdetailLayoutRouteRouteWithChildren
  AppBookAppointmentcommonLayoutRouteRoute: typeof AppBookAppointmentcommonLayoutRouteRouteWithChildren
  AppBookAppointmentSuccessRouteRoute: typeof AppBookAppointmentSuccessRouteRouteWithChildren
  AppDoctorcommonLayoutRouteRoute: typeof AppDoctorcommonLayoutRouteRouteWithChildren
  AppHospitalcommonLayoutRouteRoute: typeof AppHospitalcommonLayoutRouteRouteWithChildren
  AppNotificationcommonLayoutRouteRoute: typeof AppNotificationcommonLayoutRouteRouteWithChildren
  AppPackagecommonLayoutRouteRoute: typeof AppPackagecommonLayoutRouteRouteWithChildren
  AppProfilecommonLayoutRouteRoute: typeof AppProfilecommonLayoutRouteRouteWithChildren
  AppProfileeditLayoutRouteRoute: typeof AppProfileeditLayoutRouteRouteWithChildren
  AppSearchcommonLayoutRouteRoute: typeof AppSearchcommonLayoutRouteRouteWithChildren
  AppComponentIndexRoute: typeof AppComponentIndexRoute
  AppEntryIndexRoute: typeof AppEntryIndexRoute
  AppBookAppointmentDoctorcommonLayoutRouteRoute: typeof AppBookAppointmentDoctorcommonLayoutRouteRouteWithChildren
  AppBookAppointmentHospitalcommonLayoutRouteRoute: typeof AppBookAppointmentHospitalcommonLayoutRouteRouteWithChildren
  AppBookAppointmentPackagecommonLayoutRouteRoute: typeof AppBookAppointmentPackagecommonLayoutRouteRouteWithChildren
  AppPaymentKhqrcommonLayoutRouteRoute: typeof AppPaymentKhqrcommonLayoutRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookOfflineRouteRoute: AppBookOfflineRouteRouteWithChildren,
  AppHistoryRouteRoute: AppHistoryRouteRouteWithChildren,
  AppHomeRouteRoute: AppHomeRouteRouteWithChildren,
  AppSpecialtyRouteRoute: AppSpecialtyRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAppointmentscommonLayoutRouteRoute:
    AppAppointmentscommonLayoutRouteRouteWithChildren,
  AppAppointmentsdetailLayoutRouteRoute:
    AppAppointmentsdetailLayoutRouteRouteWithChildren,
  AppBookAppointmentcommonLayoutRouteRoute:
    AppBookAppointmentcommonLayoutRouteRouteWithChildren,
  AppBookAppointmentSuccessRouteRoute:
    AppBookAppointmentSuccessRouteRouteWithChildren,
  AppDoctorcommonLayoutRouteRoute: AppDoctorcommonLayoutRouteRouteWithChildren,
  AppHospitalcommonLayoutRouteRoute:
    AppHospitalcommonLayoutRouteRouteWithChildren,
  AppNotificationcommonLayoutRouteRoute:
    AppNotificationcommonLayoutRouteRouteWithChildren,
  AppPackagecommonLayoutRouteRoute:
    AppPackagecommonLayoutRouteRouteWithChildren,
  AppProfilecommonLayoutRouteRoute:
    AppProfilecommonLayoutRouteRouteWithChildren,
  AppProfileeditLayoutRouteRoute: AppProfileeditLayoutRouteRouteWithChildren,
  AppSearchcommonLayoutRouteRoute: AppSearchcommonLayoutRouteRouteWithChildren,
  AppComponentIndexRoute: AppComponentIndexRoute,
  AppEntryIndexRoute: AppEntryIndexRoute,
  AppBookAppointmentDoctorcommonLayoutRouteRoute:
    AppBookAppointmentDoctorcommonLayoutRouteRouteWithChildren,
  AppBookAppointmentHospitalcommonLayoutRouteRoute:
    AppBookAppointmentHospitalcommonLayoutRouteRouteWithChildren,
  AppBookAppointmentPackagecommonLayoutRouteRoute:
    AppBookAppointmentPackagecommonLayoutRouteRouteWithChildren,
  AppPaymentKhqrcommonLayoutRouteRoute:
    AppPaymentKhqrcommonLayoutRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
