name: Sync to repo B

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name "sync-bot"
          git config user.email "bot@sync.com"


      # 🔥 Commit (có thể xoá nếu không cần)
      - name: Create extra commit
        run: |
          echo "synced at $(date)" > sync.txt
          git add .
          git commit -m "chore: sync from repo A" || echo "no changes"

      # 🚀 Push chuẩn nhất (không dùng remote nữa)
      - name: Push to repo B
        run: |
          git push https://x-access-token:${{ secrets.HAOHOA }}@github.com/hali1814/teleheath-fe.git HEAD:master --force
